<a href="https://colab.research.google.com/github/dynhi/MachineLearning/blob/master/Lab8/Perceptron-MLPs/3_Lab_MLP_for_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multilayer Perceptron for Iris dataset

- Nguyễn Hữu Vũ 
- Nhóm nghiên cứu về AI đại học Bách Khoa Tp. Hồ Chí Minh

In [14]:

from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [15]:
# Load the iris dataset
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

## 1) Khám phá dữ liệu

In [16]:
X.shape

(150, 4)

In [17]:
y.shape

(150,)

In [18]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [19]:
# View the first five observations of our y data
y[:5]

array([0, 0, 0, 0, 0])

In [20]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [21]:
X_train[:5]

array([[5.4, 3.4, 1.5, 0.4],
       [5.7, 2.9, 4.2, 1.3],
       [4.9, 3.1, 1.5, 0.1],
       [6.4, 2.9, 4.3, 1.3],
       [6.2, 3.4, 5.4, 2.3]])

## 2) Chuẩn bị dữ liệu

In [22]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [23]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

In [24]:
X_train_std[:5]

array([[-0.59550469,  0.83931293, -1.37722739, -1.13099615],
       [-0.21731119, -0.31722063,  0.21252817,  0.09749967],
       [-1.2258272 ,  0.14539279, -1.37722739, -1.54049476],
       [ 0.66514032, -0.31722063,  0.271408  ,  0.09749967],
       [ 0.41301132,  0.83931293,  0.9190862 ,  1.46249503]])

In [25]:
X_test_std[:5]

array([[-1.09976269,  0.83931293, -1.37722739, -1.40399523],
       [ 0.66514032,  0.14539279,  0.97796603,  0.77999735],
       [ 1.04333382, -0.08591392,  0.80132653,  1.46249503],
       [ 2.55610783,  1.76453978,  1.50788455,  1.05299642],
       [-1.09976269, -1.70506091, -0.31739035, -0.31199894]])

## 3) Xây dựng model Perceptron

In [26]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(n_iter_no_change=40, eta0=0.1, random_state=0)
# ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0)


In [27]:

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=1000, n_iter_no_change=40, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [28]:
#The actual number of iterations to reach the stopping criterion. For multiclass fits, it is the maximum over every binary fit.
ppn.n_iter_ 

52

##### Prediction

In [29]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)
y_pred

array([0, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 2, 2, 1, 0, 1, 1, 1, 1,
       1, 0, 2, 0, 2, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0,
       0])

In [30]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.91


## 4) Xây dựng model MLPClassifier

In [31]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(8,5 ), activation='tanh', solver='sgd', 
                    alpha=0.0000001, batch_size=4, learning_rate='constant', learning_rate_init=0.005, 
                    power_t=0.5, max_iter=500, shuffle=True, random_state=11, tol=0.00001, 
                    verbose=True, warm_start=False, momentum=0.8, nesterovs_momentum=True, 
                    early_stopping=False, validation_fraction=0.2, 
                    beta_1=0.9, beta_2=0.999, epsilon=1e-08)


In [32]:

# Train the perceptron
clf.fit(X_train_std, y_train)

Iteration 1, loss = 1.04823089
Iteration 2, loss = 0.87103714
Iteration 3, loss = 0.75660196
Iteration 4, loss = 0.67071165
Iteration 5, loss = 0.60737106
Iteration 6, loss = 0.55483989
Iteration 7, loss = 0.51651946
Iteration 8, loss = 0.48657520
Iteration 9, loss = 0.45887541
Iteration 10, loss = 0.43603916
Iteration 11, loss = 0.41005798
Iteration 12, loss = 0.38937791
Iteration 13, loss = 0.36634700
Iteration 14, loss = 0.34400702
Iteration 15, loss = 0.32439396
Iteration 16, loss = 0.30519736
Iteration 17, loss = 0.28600317
Iteration 18, loss = 0.26771533
Iteration 19, loss = 0.25043015
Iteration 20, loss = 0.23622897
Iteration 21, loss = 0.22247862
Iteration 22, loss = 0.21182291
Iteration 23, loss = 0.20044989
Iteration 24, loss = 0.19144075
Iteration 25, loss = 0.18451245
Iteration 26, loss = 0.17356205
Iteration 27, loss = 0.16659779
Iteration 28, loss = 0.16103595
Iteration 29, loss = 0.15559030
Iteration 30, loss = 0.15173434
Iteration 31, loss = 0.14628540
Iteration 32, los

MLPClassifier(activation='tanh', alpha=1e-07, batch_size=4, beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(8, 5), learning_rate='constant',
              learning_rate_init=0.005, max_fun=15000, max_iter=500,
              momentum=0.8, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=11, shuffle=True, solver='sgd',
              tol=1e-05, validation_fraction=0.2, verbose=True,
              warm_start=False)

In [33]:
clf.classes_ 

array([0, 1, 2])

In [34]:
clf.n_layers_ 

4

In [35]:
clf.n_outputs_ 

3

In [36]:
clf.out_activation_ 

'softmax'

- 1 input, 2 hidden, 1 ouput: => 4
- Thông thường trong Neural Networks, sẽ ko tính input layers, nên  trong Neural Networks, trường hợp này số Layers sẽ là 3

In [37]:
# Evaluate acuracy on test data
score = clf.score(X_test_std,y_test)
print("Acuracy (on test set) = ", score)

Acuracy (on test set) =  1.0


- Ta thấy chỉ cần tăng #Layers, #Units độ chính xác sẽ tăng cao